name: 'Add Label to Cards'
description: 'Adds the given label to all cards in the given column.'
inputs:
  columns_labels:
    description: 'An array of objects each containing a column reference and an array of labels to add'
    required: true
  token:
    description: 'Token for api usage provided by github'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
